version: '3'

services:
  php:
    container_name: laravel_php
    build: .docker/php
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www:cached
    depends_on:
      - db
    networks:
      - laravel_network

  nginx:
    container_name: laravel_nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - laravel_network

  db:
    container_name: laravel_mysql
    image: mysql:8.1
    ports:
      - "3307:3306"
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/db/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - laravel_network

  phpmyadmin:
    container_name: laravel_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: laravel_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - laravel_network

  nodered:
    container_name: laravel_nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
